### ISSUE TITLE
[Bug] Coupang Parse Error

### ISSUE THREAD

**Issue by hwajin-me** [hwajin-me/hs-price-tracker#42]
### System Health details

[Bug] Coupang Parse Error

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/hwajin-me/hs-price-tracker/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

[Bug] Coupang Parse Error

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
[Bug] Coupang Parse Error
```

**Comment by hwajin-me** [comment]
https://m.coupang.com/vm/products/7701515139?failRedirectApp=true&vendorItemId=87760273771

**Comment by hwajin-me** [comment]
1. Bad Item Price
2. Bad Rocket delivery status

**Comment by hwajin-me** [comment]
This error originated from a custom integration.

Logger: custom_components.price_tracker.components.sensor
Source: custom_components/price_tracker/components/sensor.py:104
integration: E-commerce Price Tracker (documentation, issues)
First occurred: November 27, 2024 at 11:22:23 PM (1504 occurrences)
Last logged: 9:38:55 AM

Error while updating the sensor: 'arrivalMessage'
Traceback (most recent call last):
  File "/config/custom_components/price_tracker/components/sensor.py", line 104, in async_update
    data = await self._engine.load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/price_tracker/services/coupang/engine.py", line 82, in load
    delivery=coupang_parser.delivery,
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/price_tracker/services/coupang/parser.py", line 176, in delivery
    arrival = str(delivery_item["arrivalMessage"])
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'arrivalMessage'
